version: "3.8"
services:

  couchdb:
    image: couchbase-1:latest
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 4G
#        reservations:
#          cpus: '0.25'
#          memory: 500m

  reactive-poc:
    image: reactive-poc:latest
    ports:
      - 8080:8080
    depends_on:
      - couchdb
    restart: on-failure:5
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4G
        reservations:
          cpus: '0.25'
          memory: 500m

  blocking-poc:
    image: blocking-poc:latest
    ports:
      - 8090:8090
    depends_on:
      - couchdb
    restart: on-failure:5
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4G
        reservations:
          cpus: '0.25'
          memory: 500m
