version: "3.1"
services:

  couchdb:
    image: couchbase-1:latest
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210

  reactive-poc:
    image: reactive-poc:latest
    ports:
      - 8080:8080
    depends_on:
      - couchdb
    restart: on-failure:5

  blocking-poc:
    image: blocking-poc:latest
    ports:
      - 8081:8081
    depends_on:
      - couchdb
    restart: on-failure:5
