FROM gradle:jdk11 as builder

COPY --chown=gradle:gradle . /reactive-poc

WORKDIR /reactive-poc/spring-reactive-non-blocking-io

RUN gradle build --refresh-dependencies --warning-mode none -x test

EXPOSE 8080

ENTRYPOINT ["java","-jar","/reactive-poc/spring-reactive-non-blocking-io/build/libs/spring-reactive-non-blocking-io-1.0-SNAPSHOT.jar"]
