server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
  couchbase:
    bootstrap-hosts: couchdb
    bucket:
      name: test
      password: 123456
    env:
      bootstrap:
        http-direct-port: 8091